name: CI Process

on:
  push:
    branches:
      - main
      - develop
      - release/*
  pull_request:
    branches:
      - main
      - develop
      - release/*

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      
      - name: Build with Maven
        run: mvn -B compile
      
      - name: Check code style with Checkstyle
        run: mvn checkstyle:check
      
      - name: Run tests
        run: mvn test
      
      - name: Generate JaCoCo report
        run: mvn jacoco:report
        continue-on-error: true  # Continue even if this step fails due to no execution data
      
      # Only run JaCoCo checks if tests were executed
      - name: Check if test results exist
        id: check-tests
        run: |
          if [ -f target/surefire-reports ]; then
            echo "tests_ran=true" >> $GITHUB_OUTPUT
          else
            echo "tests_ran=false" >> $GITHUB_OUTPUT
          fi
      
      - name: Verify JaCoCo Coverage
        if: steps.check-tests.outputs.tests_ran == 'true'
        run: |
          echo "Checking JaCoCo coverage report..."
          if [ -f target/site/jacoco/index.html ]; then
            echo "Coverage report generated successfully."
          else
            echo "Warning: Coverage report not found. This may be normal if no tests were executed."
          fi
